"""add_oauth2_fields_to_email_account

Revision ID: cccecf203051
Revises: dcf10852d24e
Create Date: 2025-12-30 11:45:14.535730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cccecf203051'
down_revision: Union[str, None] = 'dcf10852d24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to use batch operations to alter columns
    with op.batch_alter_table('emailaccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='password'))
        batch_op.add_column(sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('token_expires_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('encrypted_password',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('updated_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailaccount', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.alter_column('encrypted_password',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.drop_column('token_expires_at')
        batch_op.drop_column('encrypted_refresh_token')
        batch_op.drop_column('encrypted_access_token')
        batch_op.drop_column('provider')
        batch_op.drop_column('auth_method')
    # ### end Alembic commands ###
