"""add_encrypted_body_to_processed_email

Revision ID: d8b67e3d3551
Revises: a00b127276e3
Create Date: 2025-12-18 15:13:07.389503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d8b67e3d3551"
down_revision: Union[str, None] = "a00b127276e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manualrule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("confidence", sa.Float(), nullable=False, server_default="1.0")
        )
        batch_op.add_column(
            sa.Column(
                "is_shadow_mode",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )
        batch_op.add_column(
            sa.Column("match_count", sa.Integer(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("processedemail", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "encrypted_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "encrypted_html", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("retention_expires_at", sa.DateTime(), nullable=True)
        )
        batch_op.alter_column("email_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("subject", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("sender", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("received_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column(
            "processed_at", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processedemail", schema=None) as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "processed_at", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column(
            "received_at", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column("sender", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("subject", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("email_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("retention_expires_at")
        batch_op.drop_column("encrypted_html")
        batch_op.drop_column("encrypted_body")

    with op.batch_alter_table("manualrule", schema=None) as batch_op:
        batch_op.drop_column("match_count")
        batch_op.drop_column("is_shadow_mode")
        batch_op.drop_column("confidence")
    # ### end Alembic commands ###
