"""Add content_hash to ProcessedEmail

Revision ID: e4ae98558c29
Revises: ecc2332e2b56
Create Date: 2025-12-24 13:45:07.191471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4ae98558c29'
down_revision: Union[str, None] = 'ecc2332e2b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processedemail', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_processedemail_content_hash'), 'processedemail', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processedemail_content_hash'), table_name='processedemail')
    op.drop_column('processedemail', 'content_hash')
    # ### end Alembic commands ###
